export const carsData = [
  {
    brand: "BMW",
    models: [
      "BMW X1",
      "BMW X3",
      "BMW X5",
      "BMW X6",
      "BMW X7",
      "BMW XM",
      "BMW iX",
      "BMW i4",
      "BMW i7",
      "BMW iX1",
      "BMW i5",
      "BMW 3 Series",
      "BMW 4 Series",
      "BMW 5 Series",
      "BMW 6 Series",
      "BMW 7 Series",
      "BMW 8 Series",
    ],
  },
  {
    brand: "TATA",
    models: [
      "Tata Bolt",
      "Tata Tiago",
      "Tata Altroz",
      "Tata Nexon",
      "Tata Harrier",
      "Tata Safari",
      "Tata Punch",
      "Tata Tigor EV",
      "Tata Nexon EV",
      "Tata Tiago.ev",
      "Tata Punch.ev",
      "Tata Harrier EV",
      "Tata Sierra",
      "Tata Sierra EV",
      "Tata Safari EV",
      "Tata Altroz EV",
      "Tata Avinya",
      "Tata Curvv",
      "Tata Curvv EV",
    ],
  },
  {
    brand: "Maruti Suzuki",
    models: [
      "Maruti Alto 800",
      "Maruti Alto K10",
      "Maruti Celerio",
      "Maruti Wagon R",
      "Maruti Swift",
      "Maruti Baleno",
      "Maruti Ignis",
      "Maruti Dzire",
      "Maruti Ciaz",
      "Maruti S-Cross",
      "Maruti Vitara Brezza",
      "Maruti Brezza",
      "Maruti Fronx",
      "Maruti Grand Vitara",
      "Maruti XL6",
      "Maruti Grand Vitara 7-Seater",
      "Maruti e Vitara",
      "Maruti Wagon R Flex Fuel",
    ],
  },
  {
    brand: "Mahindra",
    models: [
      "Mahindra Bolero",
      "Mahindra Bolero Neo",
      "Mahindra Bolero Neo Plus",
      "Mahindra Scorpio",
      "Mahindra Scorpio Classic",
      "Mahindra Scorpio-N",
      "Mahindra Thar",
      "Mahindra Thar Roxx",
      "Mahindra XUV300",
      "Mahindra XUV 3XO",
      "Mahindra XUV500",
      "Mahindra XUV700​",
      "Mahindra XUV400",
      "Mahindra BE 6",
      "Mahindra XEV 9e​",
      "Mahindra XUV 3XO EV",
      "Mahindra XEV 7e",
      "Mahindra Thar.e",
      "Mahindra BE.07",
      "Mahindra BE.09",
    ],
  },
  {
    brand: "Hyundai",
    models: [
      "Hyundai Eon",
      "Hyundai Santro",
      "Hyundai Grand i10",
      "Hyundai Grand i10 Nios",
      "Hyundai i20",
      "Hyundai i20 N Line",
      "Hyundai Xcent",
      "Hyundai Aura",
      "Hyundai Verna",
      "Hyundai Elantra​",
      "Hyundai Creta",
      "Hyundai Creta N Line",
      "Hyundai Venue",
      "Hyundai Venue N Line",
      "Hyundai Alcazar",
      "Hyundai Tucson",
      "Hyundai Exte",
      "Hyundai Kona Electric",
      "Hyundai Ioniq 5",
      "Hyundai Creta Electric",
    ],
  },
  {
    brand: "Toyota",
    models: [
      "Toyota Urban Cruiser Hyryder",
      "Toyota Urban Cruiser Taisor",
      "Toyota Fortuner",
      "Toyota Fortuner Legender",
      "Toyota Glanza",
      "Toyota Hilux",
      "Toyota Land Cruiser 300​",
      "Toyota Innova Crysta",
      "Toyota Innova Hycross",
      "Toyota Rumion",
      "Toyota Vellfire​",
      "Toyota Camry",
    ],
  },
  {
    brand: "Škoda",
    models: [
      "Škoda Slavia​",
      "Škoda Kushaq",
      "Škoda Kodiaq",
      "Škoda Kylaq​",
      "Škoda Octavia RS",
      "Škoda Superb",
    ],
  },
  {
    brand: "Kia",
    models: [
      "Kia Seltos",
      "Kia Sonet",
      "Kia Carens",
      "Kia Carnival",
      "Kia EV6",
      "Kia EV9",
      "Kia Syros",
      "Kia EV3",
      "Kia EV5",
      "Kia Carens Facelift",
      "Kia Seltos Facelift",
      "Kia Carens EV",
      "Kia Syros EV",
      "Kia Tasma",
    ],
  },
  {
    brand: "Honda",
    models: [
      "Honda WR-V",
      "Honda Elevate EV",
      "Honda CR-V (2025)",
      "Honda HR-V",
      "Honda City (2025 facelift)​",
      "Honda Amaze",
      "Honda City",
      "Honda City e:HEV (Hybrid)​",
      "Honda Elevate",
    ],
  },
];
